version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: payment_system_db
    restart: always
    environment:
      POSTGRES_DB: Payment_System
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d Payment_System"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - payment-network

  redis:
    image: redis:7-alpine
    container_name: payment_system_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - payment-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8082
      DB_URL: jdbc:postgresql://postgres:5432/Payment_System
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/payment-system
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - payment-network

networks:
  payment-network:
    name: payment-system-network
    driver: bridge

volumes:
  postgres_data:
  redis_data: