spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=validate

logging.level.com.dsavitskiy.userservice=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.liquibase=DEBUG